/*
 * This file is generated by jOOQ.
 */
package org.wallet.dao.domain;


import org.wallet.dao.domain.tables.Wallet;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.wallet</code>.
     */
    public static final Wallet WALLET = Wallet.WALLET;
}
