/*
 * This file is generated by jOOQ.
 */
package org.wallet.dao.domain.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.wallet.dao.domain.tables.Wallet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WalletRecord extends UpdatableRecordImpl<WalletRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.wallet.amount</code>.
     */
    public void setAmount(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.wallet.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.wallet.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.wallet.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletRecord
     */
    public WalletRecord() {
        super(Wallet.WALLET);
    }

    /**
     * Create a detached, initialised WalletRecord
     */
    public WalletRecord(Long amount, UUID uuid) {
        super(Wallet.WALLET);

        setAmount(amount);
        setUuid(uuid);
        resetChangedOnNotNull();
    }
}
